import {
  UtensilsCrossed, ShoppingCart, Home, Pill, Bus, Gamepad2, BookOpen,
  Shirt, Plane, Sparkles, PawPrint, Music, Dumbbell, Coffee, GraduationCap,
  Wallet, Briefcase, Gift, Wrench, Smartphone, Leaf, Wine, Clapperboard, Car,
  Tag, PiggyBank, Laptop, Gem, Baby, Heart, Star, Monitor, TrendingUp,
  ShoppingBag, PartyPopper, Building2, Banknote, BarChart3, Flower2,
  type LucideIcon,
} from "lucide-react"

export const ICON_MAP: Record<string, LucideIcon> = {
  "utensils": UtensilsCrossed,
  "shopping-cart": ShoppingCart,
  "home": Home,
  "pill": Pill,
  "bus": Bus,
  "gamepad": Gamepad2,
  "book": BookOpen,
  "shirt": Shirt,
  "plane": Plane,
  "sparkles": Sparkles,
  "paw": PawPrint,
  "music": Music,
  "dumbbell": Dumbbell,
  "coffee": Coffee,
  "graduation-cap": GraduationCap,
  "wallet": Wallet,
  "briefcase": Briefcase,
  "gift": Gift,
  "wrench": Wrench,
  "smartphone": Smartphone,
  "leaf": Leaf,
  "wine": Wine,
  "clapperboard": Clapperboard,
  "car": Car,
  "tag": Tag,
  "piggy-bank": PiggyBank,
  "laptop": Laptop,
  "gem": Gem,
  "baby": Baby,
  "heart": Heart,
  "star": Star,
  "monitor": Monitor,
  "trending-up": TrendingUp,
  "shopping-bag": ShoppingBag,
  "party-popper": PartyPopper,
  "building": Building2,
  "flower": Flower2,
  "banknote": Banknote,
  "bar-chart": BarChart3,
  // aliases for old string IDs
  "house": Home,
  "ring": Gem,
  // aliases for legacy emoji values stored in DB
  "🍕": UtensilsCrossed,
  "🛒": ShoppingCart,
  "🏠": Home,
  "💊": Pill,
  "🚌": Bus,
  "🎮": Gamepad2,
  "📚": BookOpen,
  "👗": Shirt,
  "✈️": Plane,
  "💄": Sparkles,
  "🐾": PawPrint,
  "🎵": Music,
  "🏋️": Dumbbell,
  "☕": Coffee,
  "🎓": GraduationCap,
  "💰": Wallet,
  "💼": Briefcase,
  "🎁": Gift,
  "🔧": Wrench,
  "📱": Smartphone,
  "🌿": Leaf,
  "🍷": Wine,
  "🎬": Clapperboard,
  "🚗": Car,
  "🏷️": Tag,
  "📺": Monitor,
  "📈": TrendingUp,
  "🛍️": ShoppingBag,
  "🎉": PartyPopper,
  "🏘️": Building2,
  "🌸": Flower2,
  "💻": Laptop,
  "💍": Gem,
  "👶": Baby,
  "💕": Heart,
  "⭐": Star,
  "🐷": PiggyBank,
}

export const CATEGORY_ICONS: { id: string; Icon: LucideIcon }[] = [
  { id: "utensils", Icon: UtensilsCrossed },
  { id: "shopping-cart", Icon: ShoppingCart },
  { id: "home", Icon: Home },
  { id: "pill", Icon: Pill },
  { id: "bus", Icon: Bus },
  { id: "gamepad", Icon: Gamepad2 },
  { id: "book", Icon: BookOpen },
  { id: "shirt", Icon: Shirt },
  { id: "plane", Icon: Plane },
  { id: "sparkles", Icon: Sparkles },
  { id: "paw", Icon: PawPrint },
  { id: "music", Icon: Music },
  { id: "dumbbell", Icon: Dumbbell },
  { id: "coffee", Icon: Coffee },
  { id: "graduation-cap", Icon: GraduationCap },
  { id: "wallet", Icon: Wallet },
  { id: "briefcase", Icon: Briefcase },
  { id: "gift", Icon: Gift },
  { id: "wrench", Icon: Wrench },
  { id: "smartphone", Icon: Smartphone },
  { id: "leaf", Icon: Leaf },
  { id: "wine", Icon: Wine },
  { id: "clapperboard", Icon: Clapperboard },
  { id: "car", Icon: Car },
]

export const SAVINGS_ICONS: { id: string; Icon: LucideIcon }[] = [
  { id: "piggy-bank", Icon: PiggyBank },
  { id: "home", Icon: Home },
  { id: "car", Icon: Car },
  { id: "plane", Icon: Plane },
  { id: "laptop", Icon: Laptop },
  { id: "gem", Icon: Gem },
  { id: "baby", Icon: Baby },
  { id: "heart", Icon: Heart },
  { id: "star", Icon: Star },
  { id: "gift", Icon: Gift },
]
